# Generated by Django 5.2.4 on 2025-09-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='full_name',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Full name'),
        ),
        migrations.AddField(
            model_name='company',
            name='license',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='License'),
        ),
        migrations.AddField(
            model_name='company',
            name='registration',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Registration'),
        ),
        migrations.AddField(
            model_name='company',
            name='short_name',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Short name'),
        ),
    ]
