# Generated by Django 5.2.4 on 2025-09-19 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_company_full_name_company_license_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
    ]
