# Generated by Django 5.2.4 on 2025-09-19 18:05

import django.db.models.deletion
import django_countries.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_alter_company_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyAddress',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('country', django_countries.fields.CountryField(max_length=2)),
                ('city', models.CharField(blank=True, default='', max_length=64, verbose_name='City')),
                ('street_address', models.CharField(blank=True, default='', max_length=256, verbose_name='Street address')),
                ('zip_code', models.CharField(blank=True, default='', max_length=12, verbose_name='Zip code')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='contacts.company', verbose_name='Company')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
