# Generated by Django 5.2.4 on 2025-09-23 16:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_companyaddress'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('description', models.CharField(blank=True, default='', max_length=256, verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'Contact types',
            },
        ),
        migrations.AlterModelOptions(
            name='companyaddress',
            options={'verbose_name_plural': 'Addresses'},
        ),
    ]
