# Generated by Django 5.2.4 on 2025-09-23 17:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contacttype_alter_companyaddress_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('value', models.CharField(max_length=256, verbose_name='Value')),
                ('description', models.CharField(blank=True, default='', max_length=256, verbose_name='Description')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='contacts.company', verbose_name='Company')),
                ('contact_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.contacttype', verbose_name='Contact type')),
            ],
            options={
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
