# Generated by Django 5.2.4 on 2025-09-24 17:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_companycontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('author', models.CharField(max_length=64, verbose_name='Author')),
                ('contact', models.CharField(max_length=256, verbose_name='Contact')),
                ('text', models.TextField(verbose_name='Text')),
                ('contact_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.contacttype', verbose_name='Contact type')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
