# Generated by Django 5.2.4 on 2025-09-24 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_contact'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name_plural': 'User messages'},
        ),
    ]
