# Generated by Django 5.2.4 on 2025-09-25 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_alter_contact_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_processed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Processed'),
        ),
    ]
