# Generated by Django 5.2.4 on 2025-10-03 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_contact_is_processed'),
    ]

    operations = [
        migrations.RenameModel("Contact", "UserMessage"),
    ]
