# Generated by Django 5.1.5 on 2025-02-27 10:38

import django.db.models.deletion
import listings.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('object_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listings.objecttype', verbose_name='Object type')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
    ]
