# Generated by Django 5.1.5 on 2025-02-27 10:42

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='address',
            field=models.CharField(blank=True, default='', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, max_length=64, verbose_name='City'),
        ),
        migrations.AddField(
            model_name='listing',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='BY', max_length=2, verbose_name='Country'),
        ),
    ]
