# Generated by Django 5.1.5 on 2025-02-27 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_listing_address_listing_city_listing_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Bathrooms'),
        ),
        migrations.AddField(
            model_name='listing',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Bedrooms'),
        ),
        migrations.AddField(
            model_name='listing',
            name='beds',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Beds'),
        ),
        migrations.AddField(
            model_name='listing',
            name='max_guests',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Max guests'),
        ),
    ]
