# Generated by Django 5.2.4 on 2025-08-08 09:27

import django.db.models.deletion
import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='listing',
            name='object_type',
            field=models.ForeignKey(default=listings.models.get_default_object_type, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listings.objecttype', verbose_name='Object type'),
        ),
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Slug'),
        ),
        migrations.AddField(
            model_name='listing',
            name='title',
            field=models.CharField(blank=True, max_length=64, verbose_name='Title'),
        ),
    ]
