# Generated by Django 5.1.5 on 2025-02-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_check_in_time_listing_check_out_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='listings', to='listings.amenity', verbose_name='Amenities'),
        ),
        migrations.AddField(
            model_name='listing',
            name='house_rules',
            field=models.ManyToManyField(blank=True, related_name='listings', to='listings.houserule', verbose_name='House rules'),
        ),
    ]
