# Generated by Django 5.2.4 on 2025-08-08 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_listing_description_listing_object_type_listing_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='bathrooms',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Bathrooms'),
        ),
        migrations.AddField(
            model_name='listing',
            name='bedrooms',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Bedrooms'),
        ),
        migrations.AddField(
            model_name='listing',
            name='beds',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Beds'),
        ),
        migrations.AddField(
            model_name='listing',
            name='max_guests',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Max guests'),
        ),
    ]
