# Generated by Django 5.2.4 on 2025-08-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_listing_bathrooms_listing_bedrooms_listing_beds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='amenities',
            field=models.ManyToManyField(blank=True, related_name='listings', to='listings.amenity', verbose_name='Amenities'),
        ),
        migrations.AddField(
            model_name='listing',
            name='house_rules',
            field=models.ManyToManyField(blank=True, related_name='listings', to='listings.houserule', verbose_name='House rules'),
        ),
    ]
