# Generated by Django 5.2.4 on 2025-08-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listing_amenities_listing_house_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='check_in_time',
            field=models.TimeField(null=True, verbose_name='Check-in time'),
        ),
        migrations.AddField(
            model_name='listing',
            name='check_out_time',
            field=models.TimeField(null=True, verbose_name='Check-out time'),
        ),
        migrations.AddField(
            model_name='listing',
            name='instant_booking',
            field=models.BooleanField(default=False, verbose_name='Instant booking'),
        ),
    ]
