# Generated by Django 5.2.4 on 2025-08-12 07:41

import django.db.models.deletion
import listings.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_listing_check_in_time_listing_check_out_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('index', models.PositiveSmallIntegerField(verbose_name='Index')),
                ('title', models.CharField(blank=True, default='', max_length=64, verbose_name='Title')),
                ('file', models.ImageField(upload_to=listings.models.upload_path, verbose_name='File')),
                ('is_cover', models.BooleanField(blank=True, default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='listings.listing', verbose_name='Listing')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
