# Generated by Django 5.2.4 on 2025-08-14 10:43

import django.db.models.deletion
import djmoney.models.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceTag',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(verbose_name='End date')),
                ('price_currency', djmoney.models.fields.CurrencyField(choices=[('CNY', 'Chinese Yuan'), ('EUR', 'Euro'), ('USD', 'US Dollar')], default='EUR', editable=False, max_length=3)),
                ('price', djmoney.models.fields.MoneyField(decimal_places=4, default_currency='EUR', max_digits=19)),
                ('description', models.CharField(blank=True, default='', max_length=512, verbose_name='Description')),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_tags', to='listings.listing', verbose_name='Listing')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
