# Generated by Django 5.2.4 on 2025-08-25 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_reservationstatus'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservationstatus',
            options={'verbose_name_plural': 'Reservation statuses'},
        ),
    ]
