# Generated by Django 5.2.4 on 2025-08-25 14:00

import django.db.models.deletion
import listings.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_reservationstatus_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='status',
            field=models.ForeignKey(default=listings.models.get_default_reservation_status, on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='listings.reservationstatus', verbose_name='Status'),
        ),
    ]
