# Generated by Django 5.2.4 on 2025-09-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0016_alter_amenity_name_alter_category_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservationstatus',
            name='next_statuses',
            field=models.ManyToManyField(blank=True, related_name='predecessors', to='listings.reservationstatus', verbose_name='Next statuses'),
        ),
        migrations.AddField(
            model_name='reservationstatus',
            name='previous_statuses',
            field=models.ManyToManyField(blank=True, related_name='successors', to='listings.reservationstatus', verbose_name='Previous statuses'),
        ),
    ]
