# Generated by Django 5.2 on 2025-05-15 16:00

import blog.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('uuid', models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('text', models.TextField()),
                ('title', models.CharField(max_length=64, verbose_name='Title')),
                ('excerpt', models.CharField(max_length=256, verbose_name='Excerpt')),
                ('cover', models.ImageField(null=True, upload_to=blog.models.upload_path, verbose_name='Cover')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.status', verbose_name='Status')),
                ('tags', models.ManyToManyField(related_name='posts', to='blog.tag', verbose_name='Tags')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
