# Generated by Django 5.1.5 on 2025-02-10 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_status_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='is_initial',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
