# Generated by Django 5.2.4 on 2025-08-25 13:10

import blog.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.ForeignKey(default=blog.models.get_default_status, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='blog.status', verbose_name='Status'),
        ),
    ]
