# Generated by Django 5.2.4 on 2025-09-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_status_name_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='next_statuses',
            field=models.ManyToManyField(blank=True, related_name='predecessors', to='blog.status', verbose_name='Next statuses'),
        ),
        migrations.AddField(
            model_name='status',
            name='previous_statuses',
            field=models.ManyToManyField(blank=True, related_name='successors', to='blog.status', verbose_name='Previous statuses'),
        ),
    ]
