# Generated by Django 5.1.5 on 2025-02-03 10:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='uuid',
            field=models.UUIDField(auto_created=True, default=uuid.uuid4, editable=False, null=True, verbose_name='UUID'),
        ),
    ]
