# Generated by Django 5.1.5 on 2025-02-03 10:43

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    Account = apps.get_model("accounts", "Account")
    for row in Account.objects.all():
        row.uuid = uuid.uuid4()
        row.save(update_fields=["uuid"])


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_account_uuid"),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
