# Generated by Django 5.1.1 on 2024-10-21 11:10

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='', max_length=2, verbose_name='Country'),
        ),
    ]
