# Generated by Django 5.1.1 on 2024-10-22 10:27

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_bio_profile_birth_date_profile_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.upload_path, verbose_name='Photo'),
        ),
    ]
