version: "3.9"

services:

  redis:
    container_name: redis
    image: redis:8-bookworm
    restart: always

  db:
    container_name: db
    image: postgres:14.17-bookworm
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  celery:
    container_name: celery
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.docker-dev
    build: .
    command: celery -A config worker -l INFO
    volumes:
      - .:/src
    depends_on:
      - redis
      - db

  web:
    container_name: web
    environment:
      DJANGO_SETTINGS_MODULE: config.settings.docker-test
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/src
    depends_on:
      - redis
      - db
    command: >
      sh -c "flake8 . && python manage.py test"

volumes:
  postgres_data:
